name: JMeter Test

on:
  push:
    branches:
      - main

jobs:
  run_jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t your_image_name .

      - name: Run JMeter test and copy results
        run: |
          docker run --rm -v ${{ github.workspace }}/results:/scripts/results your_image_name
          cp /scripts/results/results.jtl ${{ github.workspace }}/results.jtl
