name: JMeter CI/CD

on:
  push:
    branches:
      - main

jobs:
  run_jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t jmeter .

      - name: Run JMeter Test
        run: docker run --rm -v ${{ github.workspace }}/results:/scripts/results jmeter cp /scripts/results/results.jtl ${{ github.workspace }}/results.jtl
