name: JMeter CI/CD

on:
  push:
    branches:
      - main

jobs:
  run_jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t your-docker-image .

      - name: Run JMeter Test
        run: docker run -v $PWD:/jmeter/results your-docker-image

      - name: Archive JTL Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: /jmeter/results/results.jtl
